<?php

namespace Djemauls\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function getArticles()
	{
	/** a est un alias pour les articles    */
	$qb = $this ->createQueryBuilder("a")
				->leftJoin('a.image','i')
				->addSelect('i')

				->leftJoin('a.categories','c')
				->addSelect('c')

				->where('a.publication = :val')
				->setParameter('val', 1)

				->orderBy('a.datecreation', 'DESC');
	$query = $qb->getQuery();
	return $query->getResult();
	}

	public function getArticle($Ref)
	{
	/** a est un alias pour les articles    */
	$qb = $this ->createQueryBuilder("a")
				->leftJoin('a.image','i')
				->addSelect('i')

				->leftJoin('a.categories','c')
				->addSelect('c')

				->leftJoin('a.commentaires','k')
				->addSelect('k')

				->where('a.id = :val')
				->setParameter('val', $Ref)

				->orderBy('a.id', 'DESC');
	$query = $qb->getQuery();
	return $query->getOneOrNullResult();
	}
}
